import type { AppSpec } from '../schema/appSpec';
import { emitStandaloneEntityRoute } from './backendEmitter';
import { emitPrismaModels } from './prismaEmitter';

/**
 * Turns the loose per-entity files into an actual runnable project —
 * this is the difference between "code assembly" and "a pile of
 * files." Emits a standalone backend (its own server, its own auth if
 * requested, its own package.json) and a standalone frontend (nav
 * wiring every entity's list screen together) — genuinely `npm
 * install && npm run dev` runnable, not something you manually wire
 * into another project first.
 */
export function emitBackendScaffold(spec: AppSpec): Record<string, string> {
    const files: Record<string, string> = {};

    files['backend/package.json'] = JSON.stringify({
        name: spec.appName.toLowerCase().replace(/\s+/g, '-'),
        private: true,
        version: '1.0.0',
        scripts: {
            dev: 'node server.js',
            test: 'vitest run tests',
            'prisma:migrate': 'prisma migrate dev --name init',
            'prisma:generate': 'prisma generate',
        },
        dependencies: {
            express: '^4.19.2',
            cors: '^2.8.5',
            dotenv: '^16.4.5',
            zod: '^3.23.8',
            '@prisma/client': '^5.19.1',
            ...(spec.authentication ? { bcryptjs: '^2.4.3', jsonwebtoken: '^9.0.2' } : {}),
        },
        devDependencies: { prisma: '^5.19.1', vitest: '^2.0.5', supertest: '^7.0.0' },
    }, null, 2);

    files['backend/vitest.config.mjs'] = `import { defineConfig } from 'vitest/config';
// globals: true is what makes describe/it/expect available without an
// explicit import in every generated test file — without this, the
// generated tests in backend/tests/ fail with "describe is not defined".
export default defineConfig({ test: { globals: true } });
`;

    files['backend/.env.example'] = [
        'DATABASE_URL="postgresql://user:password@localhost:5432/' + spec.appName.toLowerCase().replace(/\s+/g, '_') + '"',
        'PORT=3000',
        spec.authentication ? 'JWT_SECRET="replace-with-a-long-random-value"' : '',
    ].filter(Boolean).join('\n') + '\n';

    const authRoutesJs = spec.authentication ? `
// Minimal auth — generated because your spec requested authentication.
// This is NOT the full auth system from the main app-making-book
// backend (no 2FA, no sessions, no rate limiting) — it's the smallest
// real, working version: register + login + password hashing + JWT.
// Upgrade to the full pattern in backend/src/routes/authRoutes.ts of
// the main project if you need those features.
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');

app.post('/api/auth/register', async (req, res) => {
  const { email, password } = req.body || {};
  if (!email || !password || password.length < 8) {
    return res.status(400).json({ error: 'email and password (min 8 chars) are required' });
  }
  const existing = await prisma.user.findUnique({ where: { email } });
  if (existing) return res.status(409).json({ error: 'Email already registered' });
  const passwordHash = await bcrypt.hash(password, 12);
  const user = await prisma.user.create({ data: { email, passwordHash } });
  res.status(201).json({ id: user.id, email: user.email });
});

app.post('/api/auth/login', async (req, res) => {
  const { email, password } = req.body || {};
  const user = await prisma.user.findUnique({ where: { email } });
  if (!user || !(await bcrypt.compare(password, user.passwordHash))) {
    return res.status(401).json({ error: 'Invalid email or password' });
  }
  const token = jwt.sign({ userId: user.id }, process.env.JWT_SECRET, { expiresIn: '7d' });
  res.json({ token });
});
` : '';

    files['backend/server.js'] = `require('dotenv').config();
const express = require('express');
const cors = require('cors');
const { PrismaClient } = require('@prisma/client');

const app = express();
const prisma = new PrismaClient();
app.use(cors());
app.use(express.json());

app.get('/health', (_req, res) => res.json({ status: 'ONLINE' }));
${authRoutesJs}
${spec.entities.map((e) => `app.use('/api/${e.name.toLowerCase()}s', require('./routes/${e.name.toLowerCase()}Routes')(prisma));`).join('\n')}

const PORT = process.env.PORT || 3000;
// Exporting \`app\` (and only listening when run directly, not when
// required by a test) is what lets backend/tests/*.test.js import this
// file and hit it with supertest without needing a real running server
// on a real port.
if (require.main === module) {
  app.listen(PORT, () => console.log('Listening on port ' + PORT));
}
module.exports = app;
`;

    files['backend/README.md'] = `# ${spec.appName} — backend

Generated by the App Builder engine (see the main project's
backend/src/builder/README.md for how). This is a real, standalone,
runnable Express + Prisma backend — not a snippet to hand-wire elsewhere.

## Run it

\`\`\`bash
cd backend
npm install
cp .env.example .env   # fill in DATABASE_URL${spec.authentication ? ' and JWT_SECRET' : ''}
npm run prisma:generate
npm run prisma:migrate
npm run dev             # http://localhost:3000
\`\`\`

## What's generated

${spec.entities.map((e) => `- \`/api/${e.name.toLowerCase()}s\` — full CRUD for ${e.name}`).join('\n')}
${spec.authentication ? '- `/api/auth/register`, `/api/auth/login` — minimal JWT auth' : ''}

## What's NOT generated

- Entity relationships (each entity is independent)
- The 2FA/sessions/rate-limiting from the main app-making-book backend —
  this is intentionally the minimal version. Copy the pattern from
  \`backend/src/routes/authRoutes.ts\` in the main project if you need it.
`;

    files['backend/prisma/schema.prisma'] = `generator client {\n  provider = "prisma-client-js"\n}\n\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\n${emitPrismaModels(spec, spec.authentication)}\n`;

    for (const entity of spec.entities) {
        files[`backend/routes/${entity.name.toLowerCase()}Routes.js`] = emitStandaloneEntityRoute(entity, spec.authentication);
    }

    return files;
}

export function emitWebScaffold(spec: AppSpec): Record<string, string> {
    const files: Record<string, string> = {};
    const entityNames = spec.entities.map((e) => e.name);

    files['web/package.json'] = JSON.stringify({
        name: spec.appName.toLowerCase().replace(/\s+/g, '-') + '-web',
        private: true,
        version: '1.0.0',
        type: 'module',
        scripts: { dev: 'vite', build: 'vite build' },
        dependencies: { react: '^18.3.1', 'react-dom': '^18.3.1' },
        devDependencies: { '@vitejs/plugin-react': '^4.3.1', vite: '^5.3.1' },
    }, null, 2);

    files['web/vite.config.js'] = `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nexport default defineConfig({ plugins: [react()] });\n`;
    files['web/index.html'] = `<!doctype html>\n<html><head><meta charset="UTF-8" /><title>${spec.appName}</title></head><body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>\n`;
    files['web/src/main.jsx'] = `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App.jsx';\nReactDOM.createRoot(document.getElementById('root')).render(<App />);\n`;

    files['web/src/App.jsx'] = `import { useState } from 'react';
${entityNames.map((n) => `import ${n}List from './generated/${n}List.jsx';`).join('\n')}

const TABS = ${JSON.stringify(entityNames)};

export default function App() {
  const [tab, setTab] = useState(TABS[0]);
  const components = { ${entityNames.map((n) => `${n}: ${n}List`).join(', ')} };
  const Active = components[tab];

  return (
    <div style={{ fontFamily: 'sans-serif', maxWidth: 700, margin: '2rem auto' }}>
      <h1>${spec.appName}</h1>
      <nav style={{ display: 'flex', gap: 8, marginBottom: 24 }}>
        {TABS.map((t) => (
          <button key={t} onClick={() => setTab(t)} style={{ fontWeight: t === tab ? 'bold' : 'normal' }}>{t}</button>
        ))}
      </nav>
      <Active />
    </div>
  );
}
`;
    return files;
}
